#!/bin/bash

cd ${0%/*} || exit 1 # Run from this directory

cd forwardStep/                    && ./Allrun
cd ../bumpMinf0675/                && ./Allrun
cd ../AxialStageMRFRotating/       && ./Allrun
cd ../AxialMixerMRFCHTSteadyState/ && ./Allrun
cd ../AxialMixerMRFCHTUnsteady/    && ./Allrun
cd ../AxialMixerMRFFSISteadyState/ && ./Allrun
cd ../AxialRotorMRF/               && ./Allrun
cd ../AxialRotorSRF/               && ./Allrun
