#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanTimeDirectories

rm -rf system/machines \
    constant/cellToRegion \
    constant/polyMesh/sets/ \
    VTK \
    > /dev/null 2>&1

find -iname "*~" | xargs rm -rf
