#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication setSet -batch setBatch
runApplication setsToZones -noFlipMap

runApplication steadyCompressibleMRFFoam

# ----------------------------------------------------------------- end-of-file
